---
title: "Mini-Project 2"
authors: "Marisa Youngblood, Tara Marin, and Jordan Moody"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(ggthemes)
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
load("individuals.rda")
```

##
We want to see what trends or patterns have emerged since the Citizens United case was decided in 2010. In particular, what has happened to political contributions from outside spenders compared to the campaign committees themselves? If there has been a notable increase, has a particular party benefitted disproportionally?

```{r}
committee_contributions <- right_join(committees, contributions, by = "cmte_id") %>%
  select(cmte_id, cmte_name, cmte_party_affiliation, cmte_type, transaction_amt)
#Joining the two data frames to connect committee types to their contributions. 


candidate_spending <- committee_contributions %>%
  select(cmte_id, cmte_name, cmte_type, cmte_party_affiliation, transaction_amt) %>%
  filter(cmte_type %in% c('P', 'S', 'H')) %>%
#Filtering for political campaign commitees from FEC Committee Type Codes.

  
outside_spending <- committee_contributions %>%
  select(cmte_id, cmte_name, cmte_type, cmte_party_affiliation, transaction_amt) %>%
  filter(cmte_type %in% c('C', 'D', 'E', 'I', 'N', 'O', 'Q', 'U', 'V', 'W', 'X', 'Y', 'Z'))
#Filtering for "independent" outside committees.  

```

```{r}
committee_spending <- candidate_spending %>%
  inner_join(contributions, by = "cmte_id")

cand_party <- committee_spending %>%
  filter(!is.na(cmte_party_affiliation)) %>%
  group_by(cmte_party_affiliation) %>%
  summarize(N = n(),
            spending = sum(transaction_amt)) %>%
  select(cmte_party_affiliation, spending)
  
#Grouping by parties for candidate spending
```
```{r}
ind_spending <- outside_spending %>%
  inner_join(contributions, by = "cmte_id")
  
ind_party <- ind_spending %>%
  filter(!is.na(cmte_party_affiliation)) %>%
  group_by(cmte_party_affiliation) %>%
  summarize(N = n(), 
            spending = sum(transaction_amt)) %>%
  select(cmte_party_affiliation, spending)

#Grouping by parties for independent spending
```

```{r}
spending <- ind_party %>%
  inner_join(cand_party, by = "cmte_party_affiliation") %>%
  rename(ind_spending = spending.x, cand_spending = spending.y) %>%
  gather(key = "spending", value = "amt", -cmte_party_affiliation)

#Joining spending into one master table to graph
```
